export const BR = {
    '001': 'Username can not be empty.',
    '003': 'The username entered is already in use.',
    '004': 'Email can not be empty.',
    '005': 'Email is invalid.',
    '006': 'Email confirmation can not be empty.',
    '007': 'Email confirmation can not be different from email.',
    '008': 'Password can not be empty.',
    '009': 'Password must be at least 8 characters long.',
    '010': 'Password confirmation can not be empty.',
    '011': 'Password confirmation can not be different from password.',
    '012': 'The email entered is already in use.',
    '013': 'The username or email can not be empty.',
    '014': 'Log in credentials are not valid.',
    '015': 'The id provided does not exist.',
    '016': 'Award name can not be empty.',
    '017': 'This award could not be created.',
    '018': 'The id provided can not be empty.',
    '019': 'The id of the award provided does not match with any of your awards.',
    '020': 'The email or username provided are already in use.',
    '021': 'You can not have two awards by the same name.',
    '022': 'No fields to update.',
    '023': 'No awards have been modified. Please check your input.',
    '024': 'No changes have been made.',
    '025': 'This question id does not correspond to this award.',
    '026': 'The url provided does not match a youtube video or image.',
    '027': 'The question provided can not be empty.',
    '028': 'The question type provided can not be empty.',
    '029': 'The question order id provided can not be empty.'
}